-- v.4.1

drop table bd_abastecimentos;
drop table bd_reparacoes_ocorrencias;
drop table bd_reparacoes_tipos;
drop table bd_anomalias;
drop table bd_ocorrencias;
drop table bd_mecanicos;
drop table bd_veiculos;
drop table bd_clientes;
drop table bd_ocorrencias_estados;



CREATE TABLE BDA_1010985.BD_ABASTECIMENTOS
  (
    IDABASTECIMENTO    NUMBER NOT NULL ,
    KM                 NUMBER NOT NULL ,
    LITROS             NUMBER NOT NULL ,
    VEICULOS_IDVEICULO NUMBER NOT NULL ,
    DATA               DATE NOT NULL
  );

CREATE UNIQUE INDEX BDA_1010985.BD_ABASTECIMENTOS_PK ON BDA_1010985.BD_ABASTECIMENTOS
  (
    IDABASTECIMENTO ASC
  );
  
ALTER TABLE BDA_1010985.BD_ABASTECIMENTOS ADD CONSTRAINT BD_ABASTECIMENTOS_PK PRIMARY KEY ( IDABASTECIMENTO ) USING INDEX BDA_1010985.BD_ABASTECIMENTOS_PK ;


CREATE TABLE BDA_1010985.BD_ANOMALIAS
  (
    IDANOMALIA NUMBER NOT NULL ,
    ANOMALIA   VARCHAR2 (255 BYTE) NOT NULL ,
    DESCRICAO CLOB ,
    VEICULOS_IDVEICULO   NUMBER NOT NULL ,
    MECANICOS_IDMECANICO NUMBER ,
    DATA                 DATE NOT NULL
  );

CREATE UNIQUE INDEX BDA_1010985.BD_ANOMALIAS_PK ON BDA_1010985.BD_ANOMALIAS
  (
    IDANOMALIA ASC
  );
ALTER TABLE BDA_1010985.BD_ANOMALIAS ADD CONSTRAINT BD_ANOMALIAS_PK PRIMARY KEY ( IDANOMALIA ) USING INDEX BDA_1010985.BD_ANOMALIAS_PK ;


CREATE TABLE BDA_1010985.BD_CLIENTES
  (
    IDCLIENTE   NUMBER NOT NULL ,
    PRIMIRONOME VARCHAR2 (50 BYTE) NOT NULL ,
    ULTIMONOME  VARCHAR2 (50 BYTE) NOT NULL ,
    EMAIL       VARCHAR2 (50 BYTE) ,
    TELEMOVEL   VARCHAR2 (15 BYTE)
  );
CREATE UNIQUE INDEX BDA_1010985.CLIENTES_PK ON BDA_1010985.BD_CLIENTES
  (
    IDCLIENTE ASC
  );
ALTER TABLE BDA_1010985.BD_CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY ( IDCLIENTE ) USING INDEX BDA_1010985.CLIENTES_PK ;


CREATE TABLE BDA_1010985.BD_MECANICOS
  (
    IDMECANICO   NUMBER NOT NULL ,
    PRIMEIRONOME VARCHAR2 (50 BYTE) NOT NULL ,
    ULTIMONOME   VARCHAR2 (50 BYTE) NOT NULL ,
    EMAIL        VARCHAR2 (50 BYTE)
  );

CREATE UNIQUE INDEX BDA_1010985.MECANICOS_PK ON BDA_1010985.BD_MECANICOS
  (
    IDMECANICO ASC
  );
ALTER TABLE BDA_1010985.BD_MECANICOS ADD CONSTRAINT MECANICOS_PK PRIMARY KEY ( IDMECANICO ) USING INDEX BDA_1010985.MECANICOS_PK ;


CREATE TABLE BDA_1010985.BD_OCORRENCIAS
  (
    IDOCORRENCIA    NUMBER NOT NULL ,
    DATAMARCACAO    DATE ,
    DATAINICIO      DATE ,
    DATAESTADOATUAL DATE ,
    KM              NUMBER ,
    PRECOTOTAL      NUMBER (10,2) ,
    OBSERVACOES_CLIENTE CLOB ,
    OBSERVACOES_MECANICO CLOB ,
    CLIENTES_IDCLIENTE             NUMBER NOT NULL ,
    MECANICOS_IDMECANICO           NUMBER NOT NULL ,
    VEICULOS_IDVEICULO             NUMBER NOT NULL ,
    OCORRENCIAS_IDOCORRENCIAESTADO NUMBER NOT NULL ,
    REPARACOES_IDREPOCORRENCIAS    NUMBER NOT NULL
  );
  
CREATE UNIQUE INDEX BDA_1010985.OCORRENCIAS_PK ON BDA_1010985.BD_OCORRENCIAS
  (
    IDOCORRENCIA ASC
  );
ALTER TABLE BDA_1010985.BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_PK PRIMARY KEY ( IDOCORRENCIA ) USING INDEX BDA_1010985.OCORRENCIAS_PK ;


CREATE TABLE BDA_1010985.BD_OCORRENCIAS_ESTADOS
  (
    IDOCORRENCIAESTADO NUMBER NOT NULL ,
    ESTADO             VARCHAR2 (30 BYTE)
  );
CREATE UNIQUE INDEX BDA_1010985.OCORRENCIAS_ESTADOS_PK ON BDA_1010985.BD_OCORRENCIAS_ESTADOS
  (
    IDOCORRENCIAESTADO ASC
  );
ALTER TABLE BDA_1010985.BD_OCORRENCIAS_ESTADOS ADD CONSTRAINT OCORRENCIAS_ESTADOS_PK PRIMARY KEY ( IDOCORRENCIAESTADO ) USING INDEX BDA_1010985.OCORRENCIAS_ESTADOS_PK ;


CREATE TABLE BDA_1010985.BD_REPARACOES_OCORRENCIAS
  (
    ID_REP_OCORRENCIAS             NUMBER NOT NULL,
    QUANTIDADE                          NUMBER NOT NULL ,
    PRECO_UNITARIO                      NUMBER (10,2) NOT NULL ,
    FK_IDREPARACAOTIPO    NUMBER NOT NULL
  );
CREATE UNIQUE INDEX BDA_1010985.REPARACOES_OCORRENCIAS_PK ON BDA_1010985.BD_REPARACOES_OCORRENCIAS
  (
    ID_REP_OCORRENCIAS ASC
  );
ALTER TABLE BDA_1010985.BD_REPARACOES_OCORRENCIAS ADD CONSTRAINT REPARACOES_OCORRENCIAS_PK PRIMARY KEY ( ID_REP_OCORRENCIAS ) USING INDEX BDA_1010985.REPARACOES_OCORRENCIAS_PK ;


CREATE TABLE BDA_1010985.BD_REPARACOES_TIPOS
  (
    IDREPARACAOTIPO NUMBER NOT NULL ,
    REPARACAO       VARCHAR2 (255 BYTE) NOT NULL ,
    DESCRICAO CLOB ,
    REPARACOES_IDREPOCORRENCIAS NUMBER NOT NULL
  );
CREATE UNIQUE INDEX BDA_1010985.REPARACOES_TIPOS_PK ON BDA_1010985.BD_REPARACOES_TIPOS
  (
    IDREPARACAOTIPO ASC
  );
ALTER TABLE BDA_1010985.BD_REPARACOES_TIPOS ADD CONSTRAINT REPARACOES_TIPOS_PK PRIMARY KEY ( IDREPARACAOTIPO ) USING INDEX BDA_1010985.REPARACOES_TIPOS_PK ;


CREATE TABLE BDA_1010985.BD_VEICULOS
  (
    IDVEICULO          NUMBER NOT NULL ,
    IDMODELO           NUMBER NOT NULL ,
    CLIENTES_IDCLIENTE NUMBER NOT NULL ,
    MARCA              VARCHAR2 (50 BYTE) NOT NULL ,
    MODELO             VARCHAR2 (50 BYTE) NOT NULL
  );
CREATE UNIQUE INDEX BDA_1010985.VEICULOS_PK ON BDA_1010985.BD_VEICULOS
  (
    IDVEICULO ASC
  );
ALTER TABLE BDA_1010985.BD_VEICULOS ADD CONSTRAINT VEICULOS_PK PRIMARY KEY ( IDVEICULO ) USING INDEX BDA_1010985.VEICULOS_PK ;


ALTER TABLE BDA_1010985.BD_ABASTECIMENTOS ADD CONSTRAINT ABASTECIMENTOS_VEICULOS_FK FOREIGN KEY ( VEICULOS_IDVEICULO ) REFERENCES BDA_1010985.BD_VEICULOS ( IDVEICULO ) NOT DEFERRABLE ;

ALTER TABLE BDA_1010985.BD_ANOMALIAS ADD CONSTRAINT ANOMALIAS_MECANICOS_FK FOREIGN KEY ( MECANICOS_IDMECANICO ) REFERENCES BDA_1010985.BD_MECANICOS ( IDMECANICO ) NOT DEFERRABLE ;

ALTER TABLE BDA_1010985.BD_ANOMALIAS ADD CONSTRAINT ANOMALIAS_VEICULOS_FK FOREIGN KEY ( VEICULOS_IDVEICULO ) REFERENCES BDA_1010985.BD_VEICULOS ( IDVEICULO ) NOT DEFERRABLE ;

ALTER TABLE BDA_1010985.BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_CLIENTES_FK FOREIGN KEY ( CLIENTES_IDCLIENTE ) REFERENCES BDA_1010985.BD_CLIENTES ( IDCLIENTE ) NOT DEFERRABLE ;

ALTER TABLE BDA_1010985.BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_ESTADOS_FK FOREIGN KEY ( OCORRENCIAS_IDOCORRENCIAESTADO ) REFERENCES BDA_1010985.BD_OCORRENCIAS_ESTADOS ( IDOCORRENCIAESTADO ) NOT DEFERRABLE ;

ALTER TABLE BDA_1010985.BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_MECANICOS_FK FOREIGN KEY ( MECANICOS_IDMECANICO ) REFERENCES BDA_1010985.BD_MECANICOS ( IDMECANICO ) NOT DEFERRABLE ;

ALTER TABLE BDA_1010985.BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_VEICULOS_FK FOREIGN KEY ( VEICULOS_IDVEICULO ) REFERENCES BDA_1010985.BD_VEICULOS ( IDVEICULO ) NOT DEFERRABLE ;

ALTER TABLE BDA_1010985.BD_OCORRENCIAS ADD CONSTRAINT REPARACOES_OCORRENCIAS_FK FOREIGN KEY ( REPARACOES_IDREPOCORRENCIAS ) REFERENCES BDA_1010985.BD_REPARACOES_OCORRENCIAS ( ID_REP_OCORRENCIAS ) NOT DEFERRABLE ;

ALTER TABLE BDA_1010985.BD_REPARACOES_OCORRENCIAS ADD CONSTRAINT TIPOS_REPARACOES_OCORR_FK FOREIGN KEY ( FK_IDREPARACAOTIPO ) REFERENCES BDA_1010985.BD_REPARACOES_TIPOS ( IDREPARACAOTIPO ) NOT DEFERRABLE ;

ALTER TABLE BDA_1010985.BD_VEICULOS ADD CONSTRAINT VEICULOS_CLIENTES_FK FOREIGN KEY ( CLIENTES_IDCLIENTE ) REFERENCES BDA_1010985.BD_CLIENTES ( IDCLIENTE ) NOT DEFERRABLE ;

CREATE SEQUENCE BDA_1010985.reparacoes_ocorrencias_reparac START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER BDA_1010985.REPARACOES_OCORRENCIAS_REPARAC BEFORE
  INSERT ON BDA_1010985.BD_REPARACOES_OCORRENCIAS FOR EACH ROW WHEN (NEW.ID_REP_OCORRENCIAS IS NULL) BEGIN :NEW.ID_REP_OCORRENCIAS := BDA_1010985.reparacoes_ocorrencias_reparac.NEXTVAL;
END;
/

