-- v.5.0.0(18.01.2017)

--tables
drop table bd_abastecimentos;
drop table bd_anomalias;
drop table bd_reparacoes_ocorrencias;
drop table bd_ocorrencias;
drop table bd_reparacoes_tipos;
drop table bd_mecanicos;
drop table bd_veiculos;
drop table bd_clientes;
drop table bd_ocorrencias_estados;

--sequences
drop sequence SEQ_IDCLIENTE;
drop sequence SEQ_IDABASTECIMENTO;
drop sequence SEQ_IDANOMALIA;
drop sequence SEQ_IDMECANICO;
drop sequence SEQ_IDOCORRENCIA;
drop sequence SEQ_IDOCORRENCIAESTADO;
drop sequence SEQ_IDREPARACAOTIPO;
drop sequence SEQ_IDVEICULO;


--triggers
drop trigger t_IDCLIENTE;
drop trigger t_IDABASTECIMENTO;
drop trigger t_IDANOMALIA;
drop trigger t_IDMECANICO;
drop trigger t_IDOCORRENCIA;
drop trigger t_IDOCORRENCIAESTADO;
drop trigger t_IDREPARACAOTIPO;
drop trigger t_IDVEICULO;


CREATE TABLE BD_ABASTECIMENTOS
  (
    IDABASTECIMENTO    NUMBER NOT NULL ,
    KM                 NUMBER NOT NULL ,
    LITROS             NUMBER NOT NULL ,
    VEICULOS_IDVEICULO NUMBER NOT NULL ,
    DATA_ABASTECIMENTO DATE NOT NULL
  );

CREATE UNIQUE INDEX BD_ABASTECIMENTOS_PK ON BD_ABASTECIMENTOS
  (
    IDABASTECIMENTO ASC
  );

ALTER TABLE BD_ABASTECIMENTOS ADD CONSTRAINT BD_ABASTECIMENTOS_PK PRIMARY KEY ( IDABASTECIMENTO ) USING INDEX BD_ABASTECIMENTOS_PK ;


CREATE TABLE BD_ANOMALIAS
  (
    IDANOMALIA NUMBER NOT NULL ,
    ANOMALIA   VARCHAR2 (255 BYTE) NOT NULL ,
    DESCRICAO CLOB ,
    VEICULOS_IDVEICULO   NUMBER NOT NULL ,
    MECANICOS_IDMECANICO NUMBER ,
    DATA_ANOMALIA DATE NOT NULL
  );

CREATE UNIQUE INDEX BD_ANOMALIAS_PK ON BD_ANOMALIAS
  (
    IDANOMALIA ASC
  );
ALTER TABLE BD_ANOMALIAS ADD CONSTRAINT BD_ANOMALIAS_PK PRIMARY KEY ( IDANOMALIA ) USING INDEX BD_ANOMALIAS_PK ;


CREATE TABLE BD_CLIENTES
  (
    IDCLIENTE   NUMBER NOT NULL ,
    PRIMIRONOME VARCHAR2 (50 BYTE) NOT NULL ,
    ULTIMONOME  VARCHAR2 (50 BYTE) NOT NULL ,
    TELEMOVEL   VARCHAR2 (15 BYTE) ,
    EMAIL       VARCHAR2 (50 BYTE) NOT NULL,
    PASSWORD    VARCHAR2 (255 BYTE) NOT NULL,
    PASSWORD_ALTERADA    NUMBER(1) default 0 not null,
    ELIMINADO    NUMBER(1) default 0 not null
  );
CREATE UNIQUE INDEX CLIENTES_PK ON BD_CLIENTES
  (
    IDCLIENTE ASC
  );
ALTER TABLE BD_CLIENTES ADD CONSTRAINT CLIENTES_PK PRIMARY KEY ( IDCLIENTE ) USING INDEX CLIENTES_PK ;


CREATE TABLE BD_MECANICOS
  (
    IDMECANICO   NUMBER NOT NULL ,
    PRIMIRONOME VARCHAR2 (50 BYTE) NOT NULL ,
    ULTIMONOME  VARCHAR2 (50 BYTE) NOT NULL ,
    TELEMOVEL   VARCHAR2 (15 BYTE) ,
    EMAIL       VARCHAR2 (50 BYTE) NOT NULL,
    PASSWORD    VARCHAR2 (255 BYTE) NOT NULL,
    ELIMINADO    NUMBER(1) default 0 not null,
    VERSAO    NUMBER not null
  );
CREATE UNIQUE INDEX MECANICOS_PK ON BD_MECANICOS
  (
    IDMECANICO ASC
  );
ALTER TABLE BD_MECANICOS ADD CONSTRAINT MECANICOS_PK PRIMARY KEY ( IDMECANICO ) USING INDEX MECANICOS_PK ;


CREATE TABLE BD_OCORRENCIAS
  (
    IDOCORRENCIA    NUMBER NOT NULL ,
    DATAMARCACAO    DATE ,
    DATAINICIO      DATE ,
    DATAESTADOATUAL DATE NOT NULL ,
    KM              NUMBER ,
    PRECOTOTAL      NUMBER (10,2) ,
    OBSERVACOES_CLIENTE CLOB ,
    OBSERVACOES_MECANICO CLOB ,
    CLIENTES_IDCLIENTE             NUMBER NOT NULL ,
    MECANICOS_IDMECANICO           NUMBER ,
    VEICULOS_IDVEICULO             NUMBER NOT NULL ,
    OCORRENCIAS_IDOCORRENCIAESTADO NUMBER NOT NULL
  );

CREATE UNIQUE INDEX OCORRENCIAS_PK ON BD_OCORRENCIAS
  (
    IDOCORRENCIA ASC
  );
ALTER TABLE BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_PK PRIMARY KEY ( IDOCORRENCIA ) USING INDEX OCORRENCIAS_PK ;


CREATE TABLE BD_OCORRENCIAS_ESTADOS
  (
    IDOCORRENCIAESTADO NUMBER NOT NULL ,
    ESTADO             VARCHAR2 (30 BYTE) NOT NULL
  );
CREATE UNIQUE INDEX OCORRENCIAS_ESTADOS_PK ON BD_OCORRENCIAS_ESTADOS
  (
    IDOCORRENCIAESTADO ASC
  );
ALTER TABLE BD_OCORRENCIAS_ESTADOS ADD CONSTRAINT OCORRENCIAS_ESTADOS_PK PRIMARY KEY ( IDOCORRENCIAESTADO ) USING INDEX OCORRENCIAS_ESTADOS_PK ;



CREATE TABLE BD_REPARACOES_OCORRENCIAS
  (
    ID_OCORRENCIAS      NUMBER NOT NULL,
    ID_REPARACAO_TIPO   NUMBER NOT NULL,
    QUANTIDADE                          NUMBER NOT NULL ,
    PRECO_UNITARIO                      NUMBER (10,2) NOT NULL
  );
ALTER TABLE BD_REPARACOES_OCORRENCIAS ADD CONSTRAINT PK_REPARACOES_OCORRENCIAS PRIMARY KEY ( ID_OCORRENCIAS, ID_REPARACAO_TIPO ) ;



CREATE TABLE BD_REPARACOES_TIPOS
  (
    IDREPARACAOTIPO NUMBER NOT NULL ,
    REPARACAO       VARCHAR2 (255 BYTE) NOT NULL ,
    DESCRICAO CLOB ,
    VERSAO    NUMBER not null
  );
CREATE UNIQUE INDEX REPARACOES_TIPOS_PK ON BD_REPARACOES_TIPOS
  (
    IDREPARACAOTIPO ASC
  );
ALTER TABLE BD_REPARACOES_TIPOS ADD CONSTRAINT REPARACOES_TIPOS_PK PRIMARY KEY ( IDREPARACAOTIPO ) USING INDEX REPARACOES_TIPOS_PK ;


CREATE TABLE BD_VEICULOS
  (
    IDVEICULO          NUMBER NOT NULL ,
    IDMODELO           NUMBER NOT NULL ,
    CLIENTES_IDCLIENTE NUMBER NOT NULL ,
    MARCA              VARCHAR2 (50 BYTE) NOT NULL ,
    MODELO             VARCHAR2 (50 BYTE) NOT NULL
  );
CREATE UNIQUE INDEX VEICULOS_PK ON BD_VEICULOS
  (
    IDVEICULO ASC
  );
ALTER TABLE BD_VEICULOS ADD CONSTRAINT VEICULOS_PK PRIMARY KEY ( IDVEICULO ) USING INDEX VEICULOS_PK ;


ALTER TABLE BD_ABASTECIMENTOS ADD CONSTRAINT ABASTECIMENTOS_VEICULOS_FK FOREIGN KEY ( VEICULOS_IDVEICULO ) REFERENCES BD_VEICULOS ( IDVEICULO ) NOT DEFERRABLE ;


ALTER TABLE BD_REPARACOES_OCORRENCIAS ADD CONSTRAINT FK_ID_OCORRENCIAS FOREIGN KEY ( ID_OCORRENCIAS ) REFERENCES BD_OCORRENCIAS ( IDOCORRENCIA ) NOT DEFERRABLE ;
ALTER TABLE BD_REPARACOES_OCORRENCIAS ADD CONSTRAINT FK_ID_REPARACAO_TIPO FOREIGN KEY ( ID_REPARACAO_TIPO ) REFERENCES BD_REPARACOES_TIPOS ( IDREPARACAOTIPO ) NOT DEFERRABLE ;


ALTER TABLE BD_ANOMALIAS ADD CONSTRAINT ANOMALIAS_MECANICOS_FK FOREIGN KEY ( MECANICOS_IDMECANICO ) REFERENCES BD_MECANICOS ( IDMECANICO ) NOT DEFERRABLE ;

ALTER TABLE BD_ANOMALIAS ADD CONSTRAINT ANOMALIAS_VEICULOS_FK FOREIGN KEY ( VEICULOS_IDVEICULO ) REFERENCES BD_VEICULOS ( IDVEICULO ) NOT DEFERRABLE ;

ALTER TABLE BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_CLIENTES_FK FOREIGN KEY ( CLIENTES_IDCLIENTE ) REFERENCES BD_CLIENTES ( IDCLIENTE ) NOT DEFERRABLE ;

ALTER TABLE BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_ESTADOS_FK FOREIGN KEY ( OCORRENCIAS_IDOCORRENCIAESTADO ) REFERENCES BD_OCORRENCIAS_ESTADOS ( IDOCORRENCIAESTADO ) NOT DEFERRABLE ;

ALTER TABLE BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_MECANICOS_FK FOREIGN KEY ( MECANICOS_IDMECANICO ) REFERENCES BD_MECANICOS ( IDMECANICO ) NOT DEFERRABLE ;

ALTER TABLE BD_OCORRENCIAS ADD CONSTRAINT OCORRENCIAS_VEICULOS_FK FOREIGN KEY ( VEICULOS_IDVEICULO ) REFERENCES BD_VEICULOS ( IDVEICULO ) NOT DEFERRABLE ;

ALTER TABLE BD_VEICULOS ADD CONSTRAINT VEICULOS_CLIENTES_FK FOREIGN KEY ( CLIENTES_IDCLIENTE ) REFERENCES BD_CLIENTES ( IDCLIENTE ) NOT DEFERRABLE ;

--Sequences
  
  CREATE SEQUENCE seq_idCliente 
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_idAbastecimento 
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_idAnomalia
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_idMecanico
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_idOcorrencia
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_idOcorrenciaEstado
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_idReparacaoTipo
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE seq_idVeiculo
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
-- Triggers

  create or replace TRIGGER t_idCliente
  BEFORE INSERT ON BD_CLIENTES
  FOR EACH ROW
BEGIN
  SELECT seq_idCliente.nextval
    INTO :new.IDCLIENTE
    FROM dual;
END;
/
  
create or replace TRIGGER t_idAbastecimento
  BEFORE INSERT ON BD_ABASTECIMENTOS
  FOR EACH ROW
BEGIN
  SELECT SEQ_IDABASTECIMENTO.nextval
    INTO :new.IDABASTECIMENTO
    FROM dual;
END;
/

create or replace TRIGGER t_idAnomalia
  BEFORE INSERT ON BD_ANOMALIAS
  FOR EACH ROW
BEGIN
  SELECT SEQ_IDANOMALIA.nextval
    INTO :new.IDANOMALIA
    FROM dual;
END;
/

create or replace TRIGGER t_idMecanico
  BEFORE INSERT ON BD_MECANICOS
  FOR EACH ROW
BEGIN
  SELECT SEQ_IDMECANICO.nextval
    INTO :new.IDMECANICO
    FROM dual;
END;
/

create or replace TRIGGER t_idOcorrencia
  BEFORE INSERT ON BD_OCORRENCIAS
  FOR EACH ROW
BEGIN
  SELECT SEQ_IDOCORRENCIA.nextval
    INTO :new.IDOCORRENCIA
    FROM dual;
END; 
/

create or replace TRIGGER t_idOcorrenciaEstado
  BEFORE INSERT ON BD_OCORRENCIAS_ESTADOS
  FOR EACH ROW
BEGIN
  SELECT SEQ_IDOCORRENCIAESTADO.nextval
    INTO :new.IDOCORRENCIAESTADO
    FROM dual;
END;
/

create or replace TRIGGER t_idReparacaoTipo
  BEFORE INSERT ON BD_REPARACOES_TIPOS
  FOR EACH ROW
BEGIN
  SELECT SEQ_IDREPARACAOTIPO.nextval
    INTO :new.IDREPARACAOTIPO
    FROM dual;
END;
/

create or replace TRIGGER t_idVeiculo
  BEFORE INSERT ON BD_VEICULOS
  FOR EACH ROW
BEGIN
  SELECT SEQ_IDVEICULO.nextval
    INTO :new.IDVEICULO
    FROM dual;
END;
/


-- CREATE SEQUENCE reparacoes_ocorrencias_reparac START WITH 1 NOCACHE ORDER ;

-- CREATE OR REPLACE TRIGGER REPARACOES_OCORRENCIAS_REPARAC BEFORE
--  INSERT ON BD_REPARACOES_OCORRENCIAS FOR EACH ROW WHEN (NEW.ID_REP_OCORRENCIAS IS NULL) BEGIN :NEW.ID_REP_OCORRENCIAS := reparacoes_ocorrencias_reparac.NEXTVAL;
-- END;


