
-- em testes

CREATE OR REPLACE PROCEDURE createUser(userNam in varchar2)
IS
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER'||userNam||'IDENTIFIED BY "pass1234" DEFAULT TABLESPACE USERS'||'QUOTA "1M" ON USERS'||
 'PASSWORD EXPIRE';
END createUser;
/