CREATE or REPLACE PROCEDURE delUser(idUser IN NUMBER)IS
 
BEGIN

savepoint erro;

DELETE
FROM BD_REPARACOES_OCORRENCIAS
WHERE BD_REPARACOES_OCORRENCIAS.ID_OCORRENCIAS IN
(
SELECT IDOCORRENCIA FROM BD_OCORRENCIAS WHERE CLIENTES_IDCLIENTE = idUser
);
 
DELETE FROM BD_ANOMALIAS
where BD_ANOMALIAS.VEICULOS_IDVEICULO IN
(
select idveiculo
from BD_VEICULOS where CLIENTES_IDCLIENTE = idUser
);
 
DELETE FROM BD_ABASTECIMENTOS
where BD_ABASTECIMENTOS.VEICULOS_IDVEICULO IN
( select idveiculo
from BD_VEICULOS where CLIENTES_IDCLIENTE = idUser
);
 
DELETE FROM BD_OCORRENCIAS
where CLIENTES_IDCLIENTE = idUser;
 
DELETE FROM bd_veiculos
where CLIENTES_IDCLIENTE = idUser;
 
DELETE FROM bd_clientes
where IDCLIENTE = idUser;
 
exception when others then rollback to erro;
 
END;
/

CREATE or REPLACE PROCEDURE delReparacaoTipo(idRepT IN NUMBER)IS
 
BEGIN

savepoint erro;

DELETE
FROM BD_REPARACOES_OCORRENCIAS
WHERE BD_REPARACOES_OCORRENCIAS.ID_REPARACAO_TIPO = idRepT;
 
DELETE
FROM BD_REPARACOES_TIPOS
where BD_REPARACOES_TIPOS.IDREPARACAOTIPO = idRepT;
 
exception when others then rollback to erro;
 
END;
/